package fox.obeliskmod.lists;

import net.minecraft.block.Block;
import net.minecraft.block.FenceBlock;
import net.minecraft.block.HorizontalBlock;
import net.minecraft.block.SlabBlock;
import net.minecraft.block.SnowBlock;
import net.minecraft.block.StairsBlock;
import net.minecraft.block.WallBlock;

public class BlockList 
{
	public static Block earth_obelisk_block;
	public static WallBlock earth_obelisk_wall;
	public static SlabBlock earth_obelisk_slab;
	public static StairsBlock earth_obelisk_stairs;
	public static FenceBlock earth_obelisk_fence;
	public static SlabBlock dirt_slab;
	public static WallBlock dirt_wall;
	public static StairsBlock dirt_stairs;
	public static WallBlock coarse_dirt_wall;
	public static SlabBlock coarse_dirt_slab;
	public static StairsBlock coarse_dirt_stairs;
	public static SlabBlock sand_slab;
	public static WallBlock sand_wall;
	public static StairsBlock sand_stairs;
	public static StairsBlock oak_log_stairs;
	public static SlabBlock oak_log_slab;
	public static WallBlock oak_log_wall;
	public static StairsBlock oak_wood_stairs;
	public static SlabBlock oak_wood_slab;
	public static WallBlock oak_wood_wall;
	public static StairsBlock spruce_log_stairs;
	public static SlabBlock spruce_log_slab;
	public static WallBlock spruce_log_wall;
	public static StairsBlock spruce_wood_stairs;
	public static SlabBlock spruce_wood_slab;
	public static WallBlock spruce_wood_wall;
	public static StairsBlock dark_oak_log_stairs;
	public static SlabBlock dark_oak_log_slab;
	public static WallBlock dark_oak_log_wall;
	public static StairsBlock dark_oak_wood_stairs;
	public static SlabBlock dark_oak_wood_slab;
	public static WallBlock dark_oak_wood_wall;
	public static StairsBlock birch_log_stairs;
	public static SlabBlock birch_log_slab;
	public static WallBlock birch_log_wall;
	public static StairsBlock birch_wood_stairs;
	public static SlabBlock birch_wood_slab;
	public static WallBlock birch_wood_wall;
	public static StairsBlock acacia_log_stairs;
	public static SlabBlock acacia_log_slab;
	public static WallBlock acacia_log_wall;
	public static StairsBlock acacia_wood_stairs;
	public static SlabBlock acacia_wood_slab;
	public static WallBlock acacia_wood_wall;
	public static StairsBlock jungle_log_stairs;
	public static SlabBlock jungle_log_slab;
	public static WallBlock jungle_log_wall;
	public static StairsBlock jungle_wood_stairs;
	public static SlabBlock jungle_wood_slab;
	public static WallBlock jungle_wood_wall;
	public static WallBlock oak_planks_wall;
	public static WallBlock spruce_planks_wall;
	public static WallBlock dark_oak_planks_wall;
	public static WallBlock birch_planks_wall;
	public static WallBlock acacia_planks_wall;
	public static WallBlock jungle_planks_wall;
	public static StairsBlock stripped_oak_wood_stairs;
	public static SlabBlock stripped_oak_wood_slab;
	public static WallBlock stripped_oak_wood_wall;
	public static StairsBlock stripped_spruce_wood_stairs;
	public static SlabBlock stripped_spruce_wood_slab;
	public static WallBlock stripped_spruce_wood_wall;
	public static StairsBlock stripped_dark_oak_wood_stairs;
	public static SlabBlock stripped_dark_oak_wood_slab;
	public static WallBlock stripped_dark_oak_wood_wall;
	public static StairsBlock stripped_birch_wood_stairs;
	public static SlabBlock stripped_birch_wood_slab;
	public static WallBlock stripped_birch_wood_wall;
	public static StairsBlock stripped_acacia_wood_stairs;
	public static SlabBlock stripped_acacia_wood_slab;
	public static WallBlock stripped_acacia_wood_wall;
	public static StairsBlock stripped_jungle_wood_stairs;
	public static SlabBlock stripped_jungle_wood_slab;
	public static WallBlock stripped_jungle_wood_wall;
	public static FenceBlock oak_wood_fence;
	public static FenceBlock spruce_wood_fence;
	public static FenceBlock dark_oak_wood_fence;
	public static FenceBlock birch_wood_fence;
	public static FenceBlock acacia_wood_fence;
	public static FenceBlock jungle_wood_fence;
	public static FenceBlock dirt_fence;
	public static FenceBlock coarse_dirt_fence;
	public static FenceBlock stone_fence;
	public static FenceBlock cobblestone_fence;
	public static FenceBlock stone_brick_fence;
	public static FenceBlock mossy_stone_brick_fence;
	public static StairsBlock red_sand_stairs;
	public static SlabBlock red_sand_slab;
	public static WallBlock red_sand_wall;
	public static SnowBlock dirt_snow;
	public static SnowBlock coarse_dirt_snow;
	public static SnowBlock oak_wood_snow;
	public static SnowBlock spruce_wood_snow;
	public static SnowBlock dark_oak_wood_snow;
	public static SnowBlock birch_wood_snow;
	public static SnowBlock acacia_wood_snow;
	public static SnowBlock jungle_wood_snow;
	public static SnowBlock sand_snow;
	public static SnowBlock red_sand_snow;
	public static SnowBlock stone_snow;
	public static SnowBlock cobblestone_snow;
	public static SnowBlock oak_planks_snow;
	public static SnowBlock spruce_planks_snow;
	public static SnowBlock dark_oak_planks_snow;
	public static SnowBlock birch_planks_snow;
	public static SnowBlock acacia_planks_snow;
	public static SnowBlock jungle_planks_snow;
	public static StairsBlock gravel_stairs;
	public static SlabBlock gravel_slab;
	public static WallBlock gravel_wall;
	public static SnowBlock gravel_snow;
	public static SnowBlock stone_brick_snow;
	public static SnowBlock mossy_stone_brick_snow;
	public static Block fire_obelisk_block;
	public static StairsBlock fire_obelisk_stairs;
	public static VertSlabBlock dirt_vert_slab;
	public static SlabBlock fire_obelisk_slab;
	public static WallBlock fire_obelisk_wall;

	
}


